/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package awesome.selenide;

public class App {
    public java.lang.Object getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
